[project]
name = "health-wellness-agent-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=0.1.0",
    "fastapi[standard]>=0.116.0",
    "openai-agents>=0.1.0",
]
